"""sync models

Revision ID: 109ab497232d
Revises: 5fa55e9d76ec
Create Date: 2025-10-08 12:32:31.210344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109ab497232d'
down_revision: Union[str, None] = '5fa55e9d76ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_profiles', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('tax_profiles', 'niit_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tax_profiles', 'carry_forward_losses',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint('uq_tax_profiles_user_id', 'tax_profiles', ['user_id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_tax_profiles_user_id', 'tax_profiles', type_='unique')
    op.alter_column('tax_profiles', 'carry_forward_losses',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tax_profiles', 'niit_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('tax_profiles', 'id')
    # ### end Alembic commands ###
