"""init schema

Revision ID: 5fa55e9d76ec
Revises: 
Create Date: 2025-10-07 15:53:08.552742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa55e9d76ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_per_share', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('account', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filing_status', sa.String(), nullable=False),
    sa.Column('federal_st_rate', sa.Float(), nullable=False),
    sa.Column('federal_lt_rate', sa.Float(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_st_rate', sa.Float(), nullable=False),
    sa.Column('state_lt_rate', sa.Float(), nullable=False),
    sa.Column('niit_rate', sa.Float(), nullable=False),
    sa.Column('carry_forward_losses', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_profiles')
    op.drop_table('lots')
    op.drop_table('users')
    # ### end Alembic commands ###
